package com.redisfront.ui.dialog;

import com.formdev.flatlaf.ui.FlatLineBorder;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.redisfront.RedisFrontApplication;

import javax.swing.*;
import java.awt.*;

public class LoadingDialog extends JDialog implements Runnable {
    private JPanel contentPane;
    private JProgressBar progressBar;
    private JButton cancelBtn;
    private final Thread thread;

    private static LoadingDialog loadingDialog;

    public LoadingDialog() {
        $$$setupUI$$$();
        setResizable(false);
        setContentPane(contentPane);
        setModal(false);
        setAlwaysOnTop(false);
        thread = new Thread(this);
        cancelBtn.addActionListener((event) -> dispose());
        progressBar.setMaximum(Integer.MAX_VALUE);
    }

    @Override
    public void pack() {
        super.pack();
        thread.start();
    }

    @Override
    public void dispose() {
        super.dispose();
        thread.interrupt();
    }

    public static void showDialog() {
        loadingDialog = new LoadingDialog();
        loadingDialog.setMinimumSize(new Dimension(500, -1));
        loadingDialog.setLocationRelativeTo(RedisFrontApplication.frame);
        loadingDialog.pack();
        loadingDialog.setVisible(true);
    }

    public static void closeDialog() {
        loadingDialog.dispose();
        loadingDialog = null;
    }

    @Override
    public void run() {
        for (int i = 0; i < Integer.MAX_VALUE; i++) {
            progressBar.setValue(i);
        }
    }

    private void createUIComponents() {
        contentPane = new JPanel();
        contentPane.setBorder(new FlatLineBorder(new Insets(1, 1, 1, 1), UIManager.getColor("Component.borderColor")));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane.setLayout(new GridLayoutManager(1, 2, new Insets(10, 10, 10, 10), -1, -1));
        progressBar = new JProgressBar();
        contentPane.add(progressBar, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelBtn = new JButton();
        cancelBtn.setText("取消");
        contentPane.add(cancelBtn, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
