package com.redisfront.ui.form.fragment;

import com.redisfront.ui.component.TextEditor;

import javax.swing.*;
import java.awt.*;

/**
 * DataChartsForm
 *
 * @author Jin
 */
public class DataChartsForm {

    private JPanel contentPanel;


    public static DataChartsForm getInstance() {
        return new DataChartsForm();
    }

    public JPanel contentPanel() {
        return contentPanel;
    }

    private void createUIComponents() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(TextEditor.newInstance());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
