package cn.devcms.redisfront.ui.form;

import net.miginfocom.layout.ConstraintParser;
import net.miginfocom.layout.LC;
import net.miginfocom.layout.UnitValue;
import net.miginfocom.swing.MigLayout;

import javax.swing.*;
import java.awt.*;

public class ControlBar {
    private JPanel contentPanel;
    private JButton button1;


    private void createUIComponents() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new MigLayout(
                "insets dialog",
                // columns
                "[fill]" +
                        "[fill]" +
                        "[fill]" +
                        "[grow,fill]" +
                        "[button,fill]",
                // rows
                "[bottom]" +
                        "[]"));
        MigLayout layout = (MigLayout) contentPanel.getLayout();
        LC lc = ConstraintParser.parseLayoutConstraint((String) layout.getLayoutConstraints());
        UnitValue[] insets = lc.getInsets();
        lc.setInsets(new UnitValue[]{
                new UnitValue(0, UnitValue.PIXEL, null),
                insets[1],
                insets[2],
                insets[3]
        });
        layout.setLayoutConstraints(lc);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPanel.setLayout(new BorderLayout(0, 0));
        final JToolBar toolBar1 = new JToolBar();
        contentPanel.add(toolBar1, BorderLayout.CENTER);
        button1 = new JButton();
        button1.setText("Button");
        toolBar1.add(button1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
