package cn.devcms.redisfront.ui.form;

import net.miginfocom.swing.MigLayout;

import javax.swing.*;
import java.awt.*;

public class MainRightForm {

    private JPanel contentPanel;
    private JTabbedPane tabbedPane1;

    public JPanel getContentPanel() {
        return contentPanel;
    }


    private void createUIComponents() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new MigLayout(
                "fill,insets panel,hidemode 3",
                // columns
                "[fill]",
                // rows
                "[fill]"));
        tabbedPane1 = new JTabbedPane();
        contentPanel.add(tabbedPane1);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
