package cn.devcms.redisfront.ui.form;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

import static com.formdev.flatlaf.FlatClientProperties.*;

public class MainLeftForm {
    private JPanel contentPanel;
    private JTabbedPane tabPanel;
    private JButton addBtn;
    private JLabel iconBtn;
    private JButton refreshBtn;

    private HomeForm homeForm;


    public JPanel getContentPanel() {
        return contentPanel;
    }

    private void createUIComponents() {
        iconBtn = new JLabel();
        iconBtn.setIcon(new FlatSVGIcon("icons/Project.svg"));
        addBtn = new JButton();
        addBtn.setIcon(new FlatSVGIcon("icons/add.svg"));
        refreshBtn = new JButton();
        refreshBtn.setIcon(new FlatSVGIcon("icons/refresh.svg"));
        tabPanel = new JTabbedPane();

        tabPanel.putClientProperty(FlatClientProperties.TABBED_PANE_TAB_ICON_PLACEMENT, SwingConstants.TOP);
        tabPanel.putClientProperty(TABBED_PANE_SHOW_TAB_SEPARATORS, true);
        tabPanel.putClientProperty(FlatClientProperties.TABBED_PANE_TAB_AREA_ALIGNMENT, TABBED_PANE_ALIGN_LEADING);
        tabPanel.putClientProperty(FlatClientProperties.TABBED_PANE_TAB_TYPE, TABBED_PANE_TAB_TYPE_CARD);

        JLabel label = new JLabel(new FlatSVGIcon("icons/icon_home.svg"), JLabel.CENTER);
        label.setBorder(new EmptyBorder(10, 0, 10, 0));
//        tabPanel.putClientProperty(TABBED_PANE_LEADING_COMPONENT, label);
        tabPanel.addTab(null, new FlatSVGIcon("icons/icon_home.svg"), new HomeForm(tabPanel).$$$getRootComponent$$$());
        tabPanel.addTab(null, new FlatSVGIcon("icons/icon_db.svg"), new JPanel());
        tabPanel.addTab(null, new FlatSVGIcon("icons/icon_command.svg"), new JPanel());
        tabPanel.addTab(null, new FlatSVGIcon("icons/icon_dashboard.svg"), new JPanel());

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        contentPanel.setEnabled(true);
        tabPanel.setTabLayoutPolicy(1);
        tabPanel.setTabPlacement(2);
        contentPanel.add(tabPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}
