package com.redisfront.ui.form;

import com.redisfront.ui.component.TextEditorComponent;

import javax.swing.*;
import java.awt.*;

public class _DashboardForm {
    private JPanel contentPanel;

    public static _DashboardForm dashboardForm;

    public static _DashboardForm getInstance() {
        if (dashboardForm == null) {
            dashboardForm = new _DashboardForm();
        }
        return dashboardForm;
    }

    public JPanel getContentPanel() {
        return contentPanel;
    }

    private void createUIComponents() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.add(TextEditorComponent.getInstance());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
