package com.redisfront.ui.form;

import cn.hutool.core.lang.Assert;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.icons.FlatSearchIcon;
import com.redisfront.model.ConnectInfo;
import com.redisfront.model.TreeNodeInfo;
import com.redisfront.util.LettuceUtil;
import com.redisfront.util.TreeUtil;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.text.JTextComponent;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.function.Consumer;

/**
 * DataSearchForm
 *
 * @author Jin
 */
public class DataSearchForm {
    private JPanel contentPanel;
    private JTree keyTree;
    private JTextField searchTextField;
    private JComboBox<Integer> databaseComboBox;
    private JButton addBtn;
    private JPanel treePanel;
    private JButton refreshBtn;

    private Consumer<TreeNodeInfo> nodeClickCallback;

    private ConnectInfo connectInfo;

    public JPanel getContentPanel() {
        return contentPanel;
    }

    public static DataSearchForm newInstance() {
        return new DataSearchForm();
    }

    public DataSearchForm() {
    }

    public DataSearchForm(Consumer<TreeNodeInfo> nodeClickCallback, ConnectInfo connectInfo) {
        this.nodeClickCallback = nodeClickCallback;
        this.connectInfo = connectInfo;
    }

    public DataSearchForm setNodeClickCallback(Consumer<TreeNodeInfo> nodeClickCallback) {
        this.nodeClickCallback = nodeClickCallback;
        return this;
    }

    public DataSearchForm setConnectInfo(ConnectInfo connectInfo) {
        this.connectInfo = connectInfo;
        return this;
    }


    public void init() {
        Assert.notNull(connectInfo, () -> new RuntimeException("connectInfo 不能为空"));
        Assert.notNull(nodeClickCallback, () -> new RuntimeException("nodeClickCallback 不能为空"));

        LettuceUtil.run(connectInfo, redisCommands -> {
            var list = redisCommands.keys("*");
            var treeModel = TreeUtil.toTreeModel(new HashSet<>(list), ":");
            keyTree.setModel(treeModel);
        });

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        contentPanel.add(panel1, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        panel2.add(databaseComboBox, BorderLayout.WEST);
        addBtn.setHorizontalAlignment(0);
        addBtn.setHorizontalTextPosition(11);
        addBtn.setText("新增");
        panel2.add(addBtn, BorderLayout.CENTER);
        refreshBtn.setText("");
        panel2.add(refreshBtn, BorderLayout.EAST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel1.add(panel3, BorderLayout.SOUTH);
        panel3.add(searchTextField, BorderLayout.CENTER);
        treePanel.setLayout(new BorderLayout(0, 0));
        contentPanel.add(treePanel, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        treePanel.add(scrollPane1, BorderLayout.CENTER);
        scrollPane1.setViewportView(keyTree);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

    private void createUIComponents() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout());
        contentPanel.setBorder(new EmptyBorder(5, 5, 5, 0));
        addBtn = new JButton();
        refreshBtn = new JButton();
        refreshBtn.setIcon(new FlatSVGIcon("icons/refresh.svg"));
        databaseComboBox = new JComboBox<>();
        var dbList = new ArrayList<>(Arrays.asList(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 16));
        for (var db : dbList) {
            databaseComboBox.addItem(db);
        }
        databaseComboBox.addActionListener(e -> {
            var db = (Integer) databaseComboBox.getSelectedItem();
            this.connectInfo.setDatabase(db);
            this.init();
        });
        treePanel = new JPanel();
        treePanel.setBorder(new EmptyBorder(3, 2, 2, 2));
        searchTextField = new JTextField();
        searchTextField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "请输入关键字...");

        var searchBtn = new JButton(new FlatSearchIcon());
        searchBtn.addActionListener(actionEvent -> LettuceUtil.run(connectInfo, redisCommands -> {
            var list = redisCommands.keys(searchTextField.getText());
            var treeModel = TreeUtil.toTreeModel(new HashSet<>(list), ":");
            keyTree.setModel(treeModel);
        }));
        searchTextField.putClientProperty(FlatClientProperties.TEXT_FIELD_TRAILING_COMPONENT, searchBtn);

        searchTextField.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        searchTextField.putClientProperty(FlatClientProperties.TEXT_FIELD_CLEAR_CALLBACK, (Consumer<JTextComponent>) textField -> LettuceUtil.run(connectInfo, redisCommands -> {
            var list = redisCommands.keys("*");
            var treeModel = TreeUtil.toTreeModel(new HashSet<>(list), ":");
            keyTree.setModel(treeModel);
        }));

        keyTree = new JTree();
        keyTree.setRootVisible(false);
        keyTree.setBorder(new EmptyBorder(5, 5, 5, 5));

    }
}
