package org.dromara.redisfront.ui.widget.main.fragment.scaffold.report;

import com.formdev.flatlaf.extras.components.FlatToggleButton;
import org.dromara.quickswing.ui.app.page.QSPageItem;
import org.dromara.redisfront.model.context.RedisConnectContext;
import org.dromara.redisfront.ui.components.chart.RedisMemoryChart;
import org.dromara.redisfront.ui.components.chart.RedisNetworkChart;
import org.dromara.redisfront.ui.widget.RedisFrontWidget;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

/**
 * DataChartsForm
 *
 * @author Jin
 */
public class ReportPageView extends QSPageItem<RedisFrontWidget> {

    private JPanel rootPanel;
    private final RedisFrontWidget owner;
    private final RedisNetworkChart redisNetworkChart;


    public ReportPageView(final RedisConnectContext redisConnectContext, RedisFrontWidget owner) {
        this.owner = owner;
        this.redisNetworkChart = new RedisNetworkChart(redisConnectContext);
        $$$setupUI$$$();
        this.rootPanel.add(redisNetworkChart, BorderLayout.CENTER);
        setupUI();
    }

    @Override
    public void updateUI() {
        if (redisNetworkChart != null) {
            redisNetworkChart.refreshUI();
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        rootPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rootPanel.add(panel1, BorderLayout.SOUTH);
        final FlatToggleButton flatToggleButton1 = new FlatToggleButton();
        flatToggleButton1.setText("网络带宽");
        panel1.add(flatToggleButton1);
        final FlatToggleButton flatToggleButton2 = new FlatToggleButton();
        flatToggleButton2.setText("内存指标");
        panel1.add(flatToggleButton2);
        final FlatToggleButton flatToggleButton3 = new FlatToggleButton();
        flatToggleButton3.setText("连接状态");
        panel1.add(flatToggleButton3);
        final FlatToggleButton flatToggleButton4 = new FlatToggleButton();
        flatToggleButton4.setText("命令统计");
        panel1.add(flatToggleButton4);
        final FlatToggleButton flatToggleButton5 = new FlatToggleButton();
        flatToggleButton5.setText(" 集群参数");
        panel1.add(flatToggleButton5);
        final FlatToggleButton flatToggleButton6 = new FlatToggleButton();
        flatToggleButton6.setText("复制监控");
        panel1.add(flatToggleButton6);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }


    @Override
    public RedisFrontWidget getApp() {
        return owner;
    }

    @Override
    protected JComponent getContentPanel() {
        return rootPanel;
    }
}
